### ISSUE TITLE
Realy Nice plugin!

### ISSUE THREAD

**Issue by D4N13L1980** [chocolf/MoneyFromMobs#1]
I have some sugestions^^

- (1) Would it be possible to show the players balance each time they collected dropped money?
- (2) Could you add an option to split the drops nicer? If a mob drops eg. 3xMoney for now it looks like that:

    You picked up $1.15!
    You picked up $1.15!
    You picked up $1.15!

    Could look like:
    You picked up $2.00!
    You picked up $1.00!
    You picked up $0.45!

- (3) Calculating the amount delayed and displaying the whole sum once like:
You picked up $3.45!

Thanks for your time and your nice plugin!

**Comment by chocolf** [comment]
Glad you like the plugin :)
For suggestion 1, this is definitely possible and I'll get on that right away.
For suggestion 2, I like the idea so I'll look into it a bit more. I might end up doing this as an addon because I want to make the main plugin as efficient as possible
For suggestion 3, I've been trying to do this for a while now because I don't like the spam messages but I can't figure out an efficient way to do it :( Just in case you haven't seen, the latest update adds holographic messages that fixes this problem kind of.
