### ISSUE TITLE
1.16.5 Issue where mobs and players will drop emeralds instead

### ISSUE THREAD

**Issue by pupshadow** [chocolf/MoneyFromMobs#3]
I have found an issue where when killing mobs and players you occasionally pickup with money except its an emerald instead and doesn't give money. 
this was working great on the last update but this update its broken.

So when you kill a mob you get emeralds which shouldn't happen you should only  get money.

server version: This server is running Paper version git-Paper-643 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by chocolf** [comment]
Hey, sorry for the late reply, I don't check github very often. Are you still experiencing this bug? do you get an error message in your console when you pick up money that turns into a normal emerald because I've been testing on Paper 1.16.5 and I can't seem to replicate the issue. It could also be another plugin that affects mob drops like Drop2Inventory
